services:
  schemes:
    restart: on-abnormal
    env_file: ./docker/.env
    build: .      
    volumes:
      - appdata:/var/www/schemes:rw
    container_name: 'schemes_fastapi'
    environment:
      - SCHEMES_PATH=/var/www/schemes/data
    networks:
      - schemes

volumes:
  appdata: {}

networks:
  schemes:
    driver: bridge
  

