services:
  schemes:
    restart: on-abnormal
    build:
      context: .. 
      dockerfile: ./docker/      
    volumes:
      - appdata:/var/www/schemes:rw
    container_name: 'schemes_web'
    environment:
      - SCHEMES_PATH=/var/www/schemes/data
    networks:
      - schemes

volumes:
  appdata: {}

networks:
  schemes:
    driver: bridge
  

